### ISSUE TITLE
The Jitpack build emits no artifacts

### ISSUE THREAD

**Issue by busti** [fdietze/vectory#45]
The latest jitback builds fail because they emit no artifacts.  
Below is a copy of the jitpack build lock found [here](https://jitpack.io/com/github/fdietze/vectory/89478c8142/build.log):  
```txt
Build starting...
Start: Sat May 16 00:59:41 UTC 2020 f6ee6fcbbf7c
Git:
89478c8
commit 89478c81425bb141471438886e26dd2d7fc91cb1
Author: Scala Steward 
Date:   Wed Apr 15 11:44:08 2020 +0200

    Update sbt to 1.3.10 (#42)


Running before_install command:
wget http://central.maven.org/maven2/org/scala-sbt/sbt-launch/1.2.8/sbt-launch-1.2.8.jar
--2020-05-16 00:59:41--  http://central.maven.org/maven2/org/scala-sbt/sbt-launch/1.2.8/sbt-launch-1.2.8.jar
Resolving central.maven.org (central.maven.org)... failed: Name or service not known.
wget: unable to resolve host address ‘central.maven.org’
Running install command:
java -jar sbt-launch-1.2.8.jar +publishM2
Error: Unable to access jarfile sbt-launch-1.2.8.jar
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
2020-05-16T00:59:44.385087656Z
Exit code: 0

ERROR: No build artifacts found
```

**Comment by busti** [comment]
Looks like this issue has been present for quite a while now.  
I have yet to find a commit that works with jitpack.

**Comment by busti** [comment]
If you are currently using jitpack I would appreciate it if you could also share your `libraryDependencies` string with me. Before I was using `"com.github.fdietze.vectory" %%% "vectory" % "<commit>"`, which worked fine so far, until I made a clean rebuild today.  
My best guess is that sbt cached some old version.

**Comment by fdietze** [comment]
Hey, sorry to hear that!

In our project, we're using
```
"com.github.fdietze.vectory" %%% "vectory" % "4931100"
```

Hope that helps to find the issue. Maybe a git bisect works to find the problematic change...

**Comment by busti** [comment]
Thanks for your reply. I will try to spend some more time on it in the coming days.  
I guess now I can just apply the fix myself if I find one, thanks a lot 👍
